!includeurl https://raw.githubusercontent.com/ssgoarango/C4-PlantUML/latest/C4.puml
' uncomment the following line and comment the first to use locally
' !include C4.puml

' Scope: A single software system.
' Primary elements: The software system in scope.
' Supporting elements: People and software systems directly connected to the software system in scope.
' Intended audience: Everybody, both technical and non-technical people, inside and outside of the software development team.

' Colors
' ##################################

!global $PERSON_BG_COLOR = "#MediumBlue"
!global $ACTUAL_PERSON_BG_COLOR = "#LightGray"
!global $SYSTEM_BG_COLOR = "#1168BD"
!global $ACTUAL_SYSTEM_BG_COLOR = "#999999"

' Styling
' ##################################

skinparam actor<<persona>> {
	StereotypeFontColor $PERSON_BG_COLOR
	'FontColor $ELEMENT_FONT_COLOR
	BackgroundColor $PERSON_BG_COLOR
	BorderColor #Navy
}

skinparam actor<<actual_persona>> {
	StereotypeFontColor $ACTUAL_PERSON_BG_COLOR
	'FontColor #Black
	BackgroundColor $ACTUAL_PERSON_BG_COLOR
	BorderColor #Silver
}

skinparam rectangle<<sistema>> {
	StereotypeFontColor $ELEMENT_FONT_COLOR
	FontColor $ELEMENT_FONT_COLOR
	BackgroundColor $SYSTEM_BG_COLOR
	BorderColor #3C7FC0
}

skinparam rectangle<<actual_sistema>> {
	StereotypeFontColor $ELEMENT_FONT_COLOR
	FontColor $ELEMENT_FONT_COLOR
	BackgroundColor $ACTUAL_SYSTEM_BG_COLOR
	BorderColor #8A8A8A
}

skinparam database<<sistema>> {
	StereotypeFontColor $ELEMENT_FONT_COLOR
	FontColor $ELEMENT_FONT_COLOR
	BackgroundColor $SYSTEM_BG_COLOR
	BorderColor #3C7FC0
}

skinparam database<<actual_sistema>> {
	StereotypeFontColor $ELEMENT_FONT_COLOR
	FontColor $ELEMENT_FONT_COLOR
	BackgroundColor $ACTUAL_SYSTEM_BG_COLOR
	BorderColor #8A8A8A
}

' Layout
' ##################################

!function LAYOUT_WITH_LEGEND()
	hide stereotype
	legend right
	|=              |= Tipo |
	|<$PERSON_BG_COLOR>      | persona |
	|<$ACTUAL_PERSON_BG_COLOR>      | persona actual |
	|<$SYSTEM_BG_COLOR>   | sistema |
	|<$ACTUAL_SYSTEM_BG_COLOR>      | sistema actual |
	endlegend
!endfunction

' Elements
' ##################################

!unquoted function Person($alias, $label)
	actor "==$label" <<persona>> as $alias
!endfunction
!unquoted function Person($alias, $label, $descr)
	actor "==$label\n\n $descr" <<persona>> as $alias
!endfunction

!unquoted function Person_Ext($alias, $label)
	actor "==$label" <<actual_persona>> as $alias
!endfunction
!unquoted function Person_Ext($alias, $label, $descr)
	actor "==$label\n\n $descr" <<actual_persona>> as $alias
!endfunction

!unquoted function System($alias, $label)
	rectangle "==$label" <<sistema>> as $alias
!endfunction
!unquoted function System($alias, $label, $descr)
	rectangle "==$label\n\n $descr" <<sistema>> as $alias
!endfunction

!unquoted function System_Ext($alias, $label)
	rectangle "==$label" <<actual_sistema>> as $alias
!endfunction
!unquoted function System_Ext($alias, $label, $descr)
	rectangle "==$label\n\n $descr" <<actual_sistema>> as $alias
!endfunction

!unquoted function SystemDb($alias, $label)
	database "==$label" <<sistema>> as $alias
!endfunction
!unquoted function SystemDb($alias, $label, $descr)
	database "==$label\n\n $descr" <<sistema>> as $alias
!endfunction

!unquoted function SystemDb_Ext($alias, $label)
	database "==$label" <<actual_sistema>> as $alias
!endfunction
!unquoted function SystemDb_Ext($alias, $label, $descr)
	database "==$label\n\n $descr" <<actual_sistema>> as $alias
!endfunction

' Boundaries
' ##################################

!unquoted function Enterprise_Boundary($alias, $label)
	!return Boundary($alias, $label, "Organización")
!endfunction
!unquoted function System_Boundary($alias, $label)
	!return Boundary($alias, $label, "Sistema")
!endfunction
